config/routes.rb
Rails.application.routes.draw do
  # set home to root and set sidepages so you dont need /main/...
  root 'main#home'
  get '/home', to: 'main#home'
  get '/add', to: 'main#add'
  get '/surprise', to: 'main#surprise'
  get '/view', to: 'main#view'
  get '/login', to: 'main#login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end

  def add
  end

  def surprise
  end

  def view
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="/view">View Recipes</a> %>
          <%# same as above but in embedded ruby %>
          <%= link_to "View Recipes", view_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/add">Share Recipes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/surprise">Surprise Me</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeProj</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/main/add.html.erb
<h1>Main#add</h1>
<p>Find me in app/views/main/add.html.erb</p>

app/views/main/home.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Main#home</h1>
</div>
<p>Find me in app/views/main/home.html.erb</p>

app/views/main/login.html.erb
<h1>Main#login</h1>
<p>Find me in app/views/main/login.html.erb</p>

app/views/main/surprise.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/home">Recipe</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
    </div class = "position">
        <button type="button" class="btn btn-primary">Left</button>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Randon</button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Meat</a></li>
                <li><a class="dropdown-item" href="#">Vegetable</a></li>
                <li><a class="dropdown-item" href="#">Drink</a></li>
            </ul>
        </div>
        <button type="button" class="btn btn-primary">Right</button>
    </div>
</nav>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
<div class="col">
    <div class="card shadow-sm">
    <%= image_tag "food1.jpg" %>
    <div class="card-body">
        <h5 class="card-title">Food title</h5>
        <p class="card-text">Food description.</p>
        <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
        </div>
        <small class="text-body-secondary">9 mins</small>
        </div>
    </div>
    </div>
</div>
<<<<<<< HEAD
</div>
=======
</div>
>>>>>>> origin/Vinter

app/views/main/view.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/home">Recipe</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                <%= image_tag "food1.jpg" %>
                <div class="card-body">
                    <h5 class="card-title">Food title</h5>
                    <p class="card-text">Food description.</p>
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                    </div>
                </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                <%= image_tag "food1.jpg" %>
                <div class="card-body">
                    <h5 class="card-title">Food title</h5>
                    <p class="card-text">Food description.</p>
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                    </div>
                </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                <%= image_tag "food1.jpg" %>
                <div class="card-body">
                    <h5 class="card-title">Food title</h5>
                    <p class="card-text">Food description.</p>
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                    </div>
                </div>
                </div>
            </div>

            <div class="col">
                <div class="card shadow-sm">
                <%= image_tag "food1.jpg" %>
                <div class="card-body">
                    <h5 class="card-title">Food title</h5>
                    <p class="card-text">Food description.</p>
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                    </div>
                </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                <%= image_tag "food1.jpg" %>
                <div class="card-body">
                    <h5 class="card-title">Food title</h5>
                    <p class="card-text">Food description.</p>
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                    </div>
                </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                <%= image_tag "food1.jpg" %>
                <div class="card-body">
                    <h5 class="card-title">Food title</h5>
                    <p class="card-text">Food description.</p>
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                    </div>
                </div>
                </div>
            </div>

            <div class="col">
                <div class="card shadow-sm">
                <%= image_tag "food1.jpg" %>
                <div class="card-body">
                    <h5 class="card-title">Food title</h5>
                    <p class="card-text">Food description.</p>
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                    </div>
                </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                <%= image_tag "food1.jpg" %>
                <div class="card-body">
                    <h5 class="card-title">Food title</h5>
                    <p class="card-text">Food description.</p>
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                    </div>
                </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                <%= image_tag "food1.jpg" %>
                <div class="card-body">
                    <h5 class="card-title">Food title</h5>
                    <p class="card-text">Food description.</p>
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                    </div>
                </div>
                </div>
            </div>

        </div>
    </div>
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
<<<<<<< HEAD
</nav>
=======
</nav>
>>>>>>> origin/Vinter